### ISSUE TITLE
Spreading object into array does nothing

### ISSUE THREAD

**Issue by alex-wilmer** [sebmarkbage/ecmascript-rest-spread#11]
This is what happens:

```
let x = { a: 1, b: 2 }
let y = [ ...x ]
y // []
```

What should happen?

Someone on my team suggested `[{ a: 1 }, { b: 2 }]` which I think is pretty cool, but I would also be in favor of a type error: `Cannot spread object inside array` or something.

**Comment by Pajn** [comment]
Another idea is that it would spread to `[['a', 1], ['b', 2]`, giving the same format as `Object.entries`

**Comment by ewinslow** [comment]
My thought is perhaps it should iterate using Sumbol.iterator property,
same as for-of. Else throw, or whatever for of already does when you try to
use it on a non-iterable. I.e. exactly what array spread syntax does
currently iiuc?

Introducing new magic semantics sounds like a bad idea.

**Comment by sebmck** [comment]
You can't add `Symbol.iterator` to `Object.prototype` because all other types in JavaScript inherit from it which means you can spread booleans and functions which doesn't make any sense.

**Comment by benlesh** [comment]
I'm probably mistaken, but wasn't there a desire to have Array Spread work with Arguments which is an "array-like" object? If so, that would seem to conflict with spreading objects into arrays pretty directly.

... again, I might be remembering that wrong.

**Comment by alex-wilmer** [comment]
This is discussed in much more detail here: https://github.com/sebmarkbage/ecmascript-rest-spread/issues/2
