### ISSUE TITLE
Object rest spread does not consider subsequent variables

### ISSUE THREAD

**Issue by rhys-vdw** [sebmarkbage/ecmascript-rest-spread#13]
Should the following use of rest spread be valid? It is currently supported by `babel-plugin-transform-object-rest-spread`.

``` js
const { ...rest, b } = { a: 'a', b: 'b' };
console.log('rest:', rest);
console.log('b:', b);

/* output:
rest: {"a":"a","b":"b"}
b: b
*/
```

@ljharb suggested that this should throw on compilation.

**Comment by ljharb** [comment]
Looks like the spec already covers this case, and it's just the babel transform that permits invalid syntax. See https://github.com/sebmarkbage/ecmascript-rest-spread/blob/master/Spec.md#syntax and https://phabricator.babeljs.io/T7265 / https://phabricator.babeljs.io/T7304.
