### ISSUE TITLE
Should Maps be spreaded?

### ISSUE THREAD

**Issue by caub** [sebmarkbage/ecmascript-rest-spread#17]
like Sets can be spread in an array, shouldn't:

`var m=new Map([[1,2],[3,4]]); JSON.stringify({...m})`

work as well?

**Comment by ewinslow** [comment]
I wouldn't think so since maps can have non-string keys.

**Comment by caub** [comment]
Yes, indeed

It could have been interesting to serialize/spread maps either with their entries `[...map] // [[k1,v1], ..]` (works) or `{...map} // {[k1.toString()]: v1, ..}` with possible losses of data for the latter, but practical.

But right, it's not necessary and just confusing

**Comment by mstade** [comment]
I suppose something like this might work:

``` javascript
[...map].reduce((o, [k, v]) => o[k] = v, {})
```

Not quite as _nice_ as `{...map}` would be. Why _not_ support spreading a Map into an Object though? If the semantics on key conversion is clear (i.e. toString ftw!) then would it really be that confusing? I'd probably find it _more_ confusing if this _didn't_ work, and in line with how confusing it was when I realized that until this proposal, spreading an object didn't work.

**Comment by caub** [comment]
that shouldn't work, more: `[...map].reduce((o, [k, v]) => ({...o, [k]: v}), {})` or `Object.assign(o, {[k]:v}))`

**Comment by mstade** [comment]
You're right, I forgot to return the object, my bad. This works fine though:

``` javascript
[...map].reduce((o, [k, v]) => (o[k] = v, o), {})
```

But workarounds aside, I'd still think it'd be meaningful if you could spread maps into objects.

**Comment by GrosSacASac** [comment]
No, because Maps are conceptually more than Objects. They can have anythings as keys.

So everyone should transform into Object, with their own custom logic, and then use the spread with that.
