### ISSUE TITLE
Hey, it's stage 3

### ISSUE THREAD

**Issue by MMeent** [sebmarkbage/ecmascript-rest-spread#21]
Yay. As seen on https://github.com/tc39/proposals, it currently is a stage 3 proposal. Updating the README.md on line 40 should be the next step, right?

PS. Thanks (!) for this proposal!

**Comment by acusti** [comment]
See #19

**Comment by forrest-akin** [comment]
Not sure who maintains this page, but it seems this needs to be updated to Stage 3 as well?
http://sebmarkbage.github.io/ecmascript-rest-spread/

**Comment by acusti** [comment]
It’s served from this repo. Just requires running the build.sh script and committing the results to the gh-pages branch.

**Comment by chicoxyzzy** [comment]
@sebmarkbage this can be closed b/c #19 was merged
