### ISSUE TITLE
Using spread in computed property names

### ISSUE THREAD

**Issue by kevinlaw91** [sebmarkbage/ecmascript-rest-spread#23]
Just came across this idea and it can be useful. Any thoughts?

``` js
let arr = ['foo1', 'foo2', 'foo3'];
let sharedData = "sameValue";

let payload = {
  [..arr]: sharedData
}
```

**Comment by benlesh** [comment]
This is interesting, but orthogonal to this proposal.

This using array destructuring to do computed property assignment on objects. First, there would need to be another proposal for computed assignment from arrays. Something like `{ ['foo1', 'foo2', 'foo3']: sharedData }`, from there you could propose `{ [...arr]: sharedData }`. In any case it seems unrelated to this proposal.

**Comment by kevinlaw91** [comment]
Good point! Closing this as this is not really fit into the proposal. But I really hope that this idea can be implemented in future if someone sees the potential. Cheers!
