### ISSUE TITLE
Bug in babel plugin?

### ISSUE THREAD

**Issue by olalonde** [sebmarkbage/ecmascript-rest-spread#24]
I'm not sure if this is a bug in the object/rest spread babel plugin, but it allows rest to be followed by other keys, e.g. https://gist.github.com/anonymous/75fdd951e66bbc5be54dbc6ef50fcdb4

Is this a bug in the plugin?

**Comment by hzoo** [comment]
aside: https://github.com/babel/babylon/releases/tag/v6.11.3 We added 2 static errors so you have to have the rest property at the end

**Comment by olalonde** [comment]
Ok thanks
