### ISSUE TITLE
Need test262 tests

### ISSUE THREAD

**Issue by littledan** [sebmarkbage/ecmascript-rest-spread#27]
To get to Stage 4 and help implementers, it'd be great to have test262 tests for this feature. cc @gsathya @sebmarkbage . Is anyone working on this yet?

**Comment by sebmarkbage** [comment]
I have not started yet. I actually didn't expect implementors to jump on it so quickly. My bad. I'm happy to start it though if you don't already have some.

**Comment by chicoxyzzy** [comment]
This can be closed as well. Tests have been landed in test262 repo
