### ISSUE TITLE
Move to tc39 organization

### ISSUE THREAD

**Issue by littledan** [sebmarkbage/ecmascript-rest-spread#28]
After a proposal reaches Stage 1, it is supposed to be in transferred to TC39, for ECMA archiving. You can do this by transferring ownership to @bterlson and then he puts it in tc39. Unfortunately, the process breaks links to the draft spec...

**Comment by bterlson** [comment]
I'm in the office today so feel free to reach out to do the transfer. Good to ping me via IRC, email, hangouts, etc. when you send it as I have a limited time to respond before the transfer expires.

**Comment by iamstarkov** [comment]
@sebmarkbage this one seems to be done now
