### ISSUE TITLE
{ let, cont} 

### ISSUE THREAD

**Issue by Preeternal** [sebmarkbage/ecmascript-rest-spread#56]
I would like to see this in relise:
`{ let x, const y, z } = functionReturnObject(w);`

**Comment by hax** [comment]
What `z` binding now? Is it also const like `y`?

**Comment by atticoos** [comment]
`z` can either be defined above, or is otherwise going to be a global

```js
var z
{let x, const y, z} = ...
```

**Comment by sebmarkbage** [comment]
This seems like it can be a plausible separate proposal but isn't related to whether we have dynamic set of keys like rest/spread.
