### ISSUE TITLE
spread with null

### ISSUE THREAD

**Issue by hangyangws** [sebmarkbage/ecmascript-rest-spread#59]
I know spread is used for array liked data.  
But I found that null also support spread.
Such as:
`let result = {...null}` 
is workd.

But, null is not array liked data.

**Comment by sebmarkbage** [comment]
This repository and your example is for object-like data. There is another form for iterables `let result = [...iterable]`.

It was decided that `null` and `undefined` are useful special cases with predictable semantics (empty list of keys). For the same reasons that they are special cases in `Object.assign`. E.g. `Object.assign({}, null)`.

**Comment by trusktr** [comment]
This just bit me. I was hunting for a bug, and eventually found the culprit to be something like

```js
var obj = { ...otherObj.someUndefinedValue }
```

An error for trying to spread an `undefined` or `null` value would've been nice and helpful.
