### ISSUE TITLE
Why is this useful grammer still in stage 3?

### ISSUE THREAD

**Issue by DanielWLam** [sebmarkbage/ecmascript-rest-spread#60]
```proposal-object-rest-spread``` seems to exist for a long while, and it was widely used. I am just a little confused why is it still at stage 3? Will it be included in ES2018?

**Comment by keithamus** [comment]
If the pull request (https://github.com/tc39/ecma262/pull/1048) is merged in this January meeting, I believe it will be included in the ES2018 spec.
